/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.72
 * Generated at: 2023-03-08 07:28:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mbelDev.utils.ScriptWriter;
import java.sql.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.jsp", Long.valueOf(1678239902481L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1678260163173L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.mbelDev.utils.ScriptWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/board.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/layout.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"header-left\"></div>\r\n");
      out.write("			<div class=\"header-center\">\r\n");
      out.write("				<ul class=\"header-center__gnb\">\r\n");
      out.write("					<li class=\"header-center__gnb-mainmenu\">\r\n");
      out.write("						우리는 누구?\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"header-center__gnb-mainmenu\">\r\n");
      out.write("						우리는 무엇을 하는가?\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"header-center__gnb-mainmenu\">\r\n");
      out.write("						우리의 시설들!\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"header-center__gnb-mainmenu\">\r\n");
      out.write("						우리의 활동!\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"header-center__gnb-mainmenu\">\r\n");
      out.write("						우리를 찾아오라!\r\n");
      out.write("					</li>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"header-right\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("UTF-8");
String idx = request.getParameter("idx");

//DB에 연결
String driver = "oracle.jdbc.OracleDriver";
String url = "jdbc:oracle:thin:@localhost:1521:xe";
String id = "gundam";
String pw = "EFSFsaikou0079";

Connection conn = null;
PreparedStatement psmt = null;
ResultSet result = null;

String postNo = null;
String userNM = null;
String subject = null;
String contents = null;
String userDate = null;

String sql = "SELECT * FROM BOARD WHERE NO = ?";

try {
	Class.forName(driver);
	conn = DriverManager.getConnection(url, id, pw);
	psmt = conn.prepareStatement(sql);
	psmt.setString(1, idx);
	result = psmt.executeQuery();
	if (result.next()) {
		postNo = result.getString("NO");
		userNM = result.getString("userNM");
		subject = result.getString("subject");
		contents = result.getString("contents");
		userDate = result.getString("userDate");
	}
} catch (Exception e) {
	e.printStackTrace();
} finally {
	if (psmt != null)
		psmt.close();
	if (conn != null)
		conn.close();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("	<p>view입니다.</p>\r\n");
      out.write("	<div class=\"post\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<button class=\"btn return\">게시판으로 돌아가기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr class=\"post-no\">\r\n");
      out.write("						<td>No.</td>\r\n");
      out.write("						<th>");
      out.print(postNo);
      out.write("</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"post-title\">\r\n");
      out.write("						<td>제목</td>\r\n");
      out.write("						<th>");
      out.print(subject);
      out.write("</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"post-author\">\r\n");
      out.write("						<td>글쓴이</td>\r\n");
      out.write("						<th>");
      out.print(userNM);
      out.write("</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"post-date\">\r\n");
      out.write("						<td>작성일자</td>\r\n");
      out.write("						<th>");
      out.print(userDate);
      out.write("</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class=\"post-contents\">\r\n");
      out.write("						<td>내용</td>\r\n");
      out.write("						<th>");
      out.print(contents);
      out.write("</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button>\r\n");
      out.write("					<a href=\"modify.jsp?idx=");
      out.print(idx);
      out.write("\">수정하기</a>\r\n");
      out.write("				</button>\r\n");
      out.write("				<button>\r\n");
      out.write("					<a href=\"delete.jsp?idx=");
      out.print(idx);
      out.write("\">삭제하기</a>\r\n");
      out.write("				</button>\r\n");
      out.write("				<button>\r\n");
      out.write("					<a href=\"list.jsp\">돌아가기</a>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("	\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
